name = "x-profile-menu-website"
compatibility_date = "2024-01-15"

[env.production]
name = "x-profile-menu-website"

[env.preview]
name = "x-profile-menu-website-preview"

# Pages 配置
pages_build_output_dir = "out"
